name: Update Endpoint

on: 
  workflow_dispatch:
    inputs:
      args: 
        description: 'optional arguments for make function'
        default: ''

jobs:
  update_endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export environment variables
        uses: HatsuneMiku3939/direnv-action@v1
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Update endpoint
        run: make update_endpoint ARGS=${{ github.event.inputs.args }}
